
import React from 'react';

interface InterpretationProps {
  summary: string;
}

const Interpretation: React.FC<InterpretationProps> = ({ summary }) => {
  return (
    <section className="relative bg-white border border-blue-100 rounded-xl shadow-sm mb-8 overflow-hidden">
      {/* AI Decorator Header */}
      <div className="bg-gradient-to-r from-blue-50 to-white px-6 py-3 border-b border-blue-50 flex items-center gap-2">
        <div className="p-1.5 bg-blue-600 rounded-lg shadow-sm">
          <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
          </svg>
        </div>
        <h2 className="text-lg font-bold text-slate-800">AI Comprehensive Interpretation</h2>
      </div>

      <div className="p-6">
        <div className="prose prose-sm prose-blue max-w-none">
          <p className="text-slate-700 leading-7 text-base">
            {summary}
          </p>
        </div>
        
        <div className="mt-4 pt-4 border-t border-slate-100 flex items-center justify-between">
            <span className="text-xs text-slate-400 font-medium">Generated by EnrichRAG Model v1.0</span>
            <div className="flex gap-2">
                <button className="text-xs text-slate-500 hover:text-blue-600 border border-slate-200 px-2 py-1 rounded hover:bg-slate-50 transition-colors">Copy</button>
                <button className="text-xs text-slate-500 hover:text-blue-600 border border-slate-200 px-2 py-1 rounded hover:bg-slate-50 transition-colors">Regenerate</button>
            </div>
        </div>
      </div>
    </section>
  );
};

export default Interpretation;
